apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: secure-api
  namespace: default
  labels:
    app.kubernetes.io/name: secure-api
    app.kubernetes.io/part-of: secure-k8s-devsecops
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: secure-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
