apiVersion: v1
kind: Service
metadata:
  name: secure-api
  namespace: default
  labels:
    app.kubernetes.io/name: secure-api
    app.kubernetes.io/part-of: secure-k8s-devsecops
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secure-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
